language: node_js
node_js:
  - "8"

before_install:
  - yarn add codecov

script:
  - yarn install
  - yarn lint
  - yarn test
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - export TAG=${TAG//\//-}
  - docker build -t onsdigital/eq-publisher:$TAG --build-arg APPLICATION_VERSION=$(git rev-parse HEAD) -f Dockerfile .
  - echo "Pushing with tag [$TAG]"
  - docker push onsdigital/eq-publisher:$TAG

after_success:
 - codecov

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master
    - /^greenkeeper/.*$/
